CREATE DATABASE IF NOT EXISTS camagru CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE IF NOT EXISTS camagru.USER (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mail VARCHAR(50) NOT NULL UNIQUE,
  username VARCHAR(30) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  recovery TEXT DEFAULT NULL
);